# Generated by Django 2.2.5 on 2020-11-06 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('airplane_name', models.CharField(choices=[('oneway', 'One Way'), ('roundtrip', 'Round Trip')], max_length=50, null=True)),
                ('starting_point', django_countries.fields.CountryField(max_length=2)),
                ('destination', django_countries.fields.CountryField(max_length=2)),
                ('flight_name', models.CharField(choices=[('daehan', 'Daehan'), ('asiana', 'Asiana'), ('jeju', 'Jeju'), ('airforce', 'Airforce')], max_length=50, null=True)),
                ('_departure', models.DateField(default='', null=True)),
                ('_return', models.DateField(default='', null=True)),
                ('adult', models.IntegerField()),
                ('children', models.IntegerField()),
                ('flight_class', models.CharField(blank=True, choices=[('economy', 'Economy'), ('business', 'Business'), ('firstclass', 'First Class')], max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
