# Generated by Django 2.2.5 on 2020-11-06 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airplanes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airplane',
            old_name='airplane_name',
            new_name='ticket',
        ),
    ]
