# Generated by Django 2.2.5 on 2020-11-05 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airplanes', '0002_auto_20201105_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airplanes',
            name='_departure',
            field=models.DateTimeField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='airplanes',
            name='_return',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='airplanes',
            name='take_time',
            field=models.TimeField(blank=True, default='', null=True),
        ),
    ]
