# Generated by Django 2.2.5 on 2020-11-07 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airplanes', '0002_auto_20201107_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airplane',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airplanes', to=settings.AUTH_USER_MODEL),
        ),
    ]
