# Generated by Django 2.2.5 on 2020-11-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airplanes', '0003_auto_20201105_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airplanes',
            name='_departure',
            field=models.DateField(blank=True, default='', null=True),
        ),
    ]
