# Generated by Django 2.2.5 on 2020-11-12 02:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('airplanes', '0003_auto_20201107_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airplane',
            name='user',
        ),
        migrations.AddField(
            model_name='airplane',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='airplanes', to=settings.AUTH_USER_MODEL),
        ),
    ]
