# Generated by Django 2.2.5 on 2020-11-05 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airplanes', '0004_auto_20201105_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airplanes',
            old_name='way',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='airplanes',
            name='_departure',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='airplanes',
            name='_return',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='airplanes',
            name='take_time',
            field=models.TimeField(null=True),
        ),
    ]
