# Generated by Django 2.2.5 on 2020-11-17 01:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('airplanes', '0004_auto_20201112_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airplane',
            name='user',
        ),
        migrations.AddField(
            model_name='airplane',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='airplanes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
