# Generated by Django 2.2.5 on 2020-11-05 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('airplanes', '0005_auto_20201105_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airplanes',
            name='destination',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='airplanes',
            name='flight_class',
            field=models.CharField(blank=True, choices=[('economy', 'Economy'), ('business', 'Business'), ('firstclass', 'First Class')], max_length=30),
        ),
        migrations.AlterField(
            model_name='airplanes',
            name='flight_name',
            field=models.CharField(choices=[('daehan', 'Daehan'), ('asiana', 'Asiana'), ('jeju', 'Jeju'), ('airforce', 'Airforce')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='airplanes',
            name='name',
            field=models.CharField(choices=[('oneway', 'One Way'), ('roundtrip', 'Round Trip')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='airplanes',
            name='starting_point',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='airplanes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
