# Generated by Django 2.2.5 on 2020-12-09 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_auto_20201209_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('peding', 'Pending'), ('confirmed', 'Confirmed'), ('canceled', 'Canceled')], max_length=20),
        ),
    ]
