# Generated by Django 2.2.5 on 2020-12-04 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20201107_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='five_score',
        ),
        migrations.RemoveField(
            model_name='review',
            name='one_score',
        ),
        migrations.RemoveField(
            model_name='review',
            name='ten_score',
        ),
    ]
